#########################################
# Base Ubuntu Installation
# (C) MetaMagic Global Inc, NJ, USA, 2017
#
# Desire3D Micro Services Containers
#########################################

# Base OS Version
FROM metamagicglobal/ubuntu

 ADD JDK8 

# when the container launches
CMD ["bash"] 
