apiVersion: v1
kind: Service
metadata:
  name: productreviewservice
  namespace: shoppingportal-hpa
spec:
  type: LoadBalancer
  selector: 
    name: productreview
  ports:
  - protocol: TCP
    targetPort: 8082
    port: 80
    name: http

