apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hello-deploy
  namespace: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      desire3d.io/name: hello
      desire3d.io/zone: prod
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        desire3d.io/name: hello
        desire3d.io/version: "1.0.2"
        desire3d.io/release: stable
        desire3d.io/tier: fe
        desire3d.io/zone: prod
        desire3d.io/managed-by: m2
    spec:
      containers:
        - name: hello-ctr-2
          image: metamagicglobal/hello:v1.1
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 80
