kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs
  namespace: omega-efs
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi